name: Build and Release RunIt Binary

on:
  push:
    tags:
      - 'v*'  
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows]
        arch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.2"

      - name: Install dependencies
        run: go mod tidy

      - name: Build binary
        run: |
          mkdir -p build
          CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o build/runit-${{ matrix.os }}-${{ matrix.arch }}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
